-- Load main schema
\i '/docker-entrypoint-initdb.d/schema.sql'

-- Load views
\i '/docker-entrypoint-initdb.d/views/active_listings.sql'
\i '/docker-entrypoint-initdb.d/views/active_users.sql'
\i '/docker-entrypoint-initdb.d/views/ads_without_offers.sql'
\i '/docker-entrypoint-initdb.d/views/bookmarked_ads.sql'
\i '/docker-entrypoint-initdb.d/views/frequently_reported_ads.sql'
\i '/docker-entrypoint-initdb.d/views/incoming_offers.sql'
\i '/docker-entrypoint-initdb.d/views/moderator_performance.sql'
\i '/docker-entrypoint-initdb.d/views/pending_offers.sql'
\i '/docker-entrypoint-initdb.d/views/purchased_vehicles.sql'
\i '/docker-entrypoint-initdb.d/views/report_metrics.sql'
\i '/docker-entrypoint-initdb.d/views/reported_listings.sql'
\i '/docker-entrypoint-initdb.d/views/reports_per_mod.sql'
\i '/docker-entrypoint-initdb.d/views/resolved_reports.sql'
\i '/docker-entrypoint-initdb.d/views/sales_history.sql'
\i '/docker-entrypoint-initdb.d/views/seller_ads.sql'
\i '/docker-entrypoint-initdb.d/views/seller_ratings.sql'
\i '/docker-entrypoint-initdb.d/views/system_metrics.sql'
\i '/docker-entrypoint-initdb.d/views/unresolved_reports.sql'
\i '/docker-entrypoint-initdb.d/views/user_report_history.sql'

-- Load triggers
\i '/docker-entrypoint-initdb.d/triggers/change_offer_on_transaction_creation.sql'
\i '/docker-entrypoint-initdb.d/triggers/close_ad_after_sale.sql'
\i '/docker-entrypoint-initdb.d/triggers/close_report_on_ad_delete.sql'
\i '/docker-entrypoint-initdb.d/triggers/create_bookmark_list_on_first_login.sql'
\i '/docker-entrypoint-initdb.d/triggers/prevent_ad_deletion_with_pending_offers.sql'
\i '/docker-entrypoint-initdb.d/triggers/prevent_admin_deletion.sql'
\i '/docker-entrypoint-initdb.d/triggers/prevent_duplicate_reviews.sql'
\i '/docker-entrypoint-initdb.d/triggers/prevent_mod_deletion_with_active_reports.sql'
\i '/docker-entrypoint-initdb.d/triggers/prevent_negative_balance_on_insert.sql'
\i '/docker-entrypoint-initdb.d/triggers/prevent_price_update_after_accept.sql'
\i '/docker-entrypoint-initdb.d/triggers/prevent_transaction_updates.sql'
\i '/docker-entrypoint-initdb.d/triggers/reject_offers_on_price_change.sql'
\i '/docker-entrypoint-initdb.d/triggers/resolve_pending_offers_on_ad_deletion.sql'
\i '/docker-entrypoint-initdb.d/triggers/set_report_resoulution_date_on_closure.sql'
\i '/docker-entrypoint-initdb.d/triggers/update_ad_status_on_offer_acceptence.sql'
